package com.edysmajler.neweracore.command;

import com.edysmajler.neweracore.config.PluginConfig;
import com.edysmajler.neweracore.plan.PlannedSite;
import com.edysmajler.neweracore.plan.TerrainClass;
import com.edysmajler.neweracore.plan.WorldQuery;
import com.edysmajler.neweracore.plan.WorldSnapshot;
import com.edysmajler.neweracore.world.WorldEngine;
import dev.jorel.commandapi.executors.CommandArguments;
import dev.jorel.commandapi.executors.PlayerCommandExecutor;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import org.bukkit.Chunk;
import org.bukkit.ChunkSnapshot;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;
import org.bukkit.scheduler.BukkitRunnable;

/**
 * Samples a square of world into a snapshot file the world planner can open.
 *
 * <p>This command exists because of a boundary that cannot be argued with. Every decision the
 * engine makes is a pure function of the seed and can be recomputed anywhere, but the ground those
 * decisions are made about is Mojang's generator, reachable only by generating chunks. So the
 * planner cannot show you your world; only a server can, once, and then the planner reads what it
 * wrote.
 *
 * <p>It refuses to run while the engine is enabled, and that refusal is the important part. Chunks
 * generated by this scan are only ever new once: whatever the engine did or did not do to them at
 * that moment is permanent. Exporting from a live world would either bake corruption into the map a
 * designer is trying to read as untouched terrain, or — if the engine were merely suspended for the
 * scan — leave tens of thousands of chunks vanilla forever, which is precisely the "generated
 * before the plugin was installed" failure that {@code /nec here} exists to explain. Export from a
 * scratch world with {@code world-engine.enabled: false}, plan against it, and generate the real
 * world afterwards.
 */
public class Export implements PlayerCommandExecutor {

  /** Name of the argument holding the width of the area to sample. */
  public static final String SIZE = "size";

  /** Name of the argument holding how many blocks one sample stands for. */
  public static final String RESOLUTION = "resolution";

  /** Width sampled when the command is given no size, matching the planned playable area. */
  public static final int DEFAULT_SIZE = 3000;

  /** Blocks per sample when the command is given no resolution. */
  public static final int DEFAULT_RESOLUTION = 4;

  /** Chunks generated per tick, kept low so a scan does not starve the rest of the server. */
  private static final int CHUNKS_PER_TICK = 4;

  /** How many chunk loads may be outstanding at once. */
  private static final int IN_FLIGHT = 16;

  /** Where snapshots are written, under the plugin's data folder. */
  private static final String FOLDER = "plans";

  private final PluginConfig config;
  private final Plugin plugin;
  private final WorldEngine engine;

  /**
   * Creates the executor.
   *
   * @param config the loaded plugin configuration
   * @param plugin the plugin instance, for its scheduler and data folder
   * @param engine the running world engine, which owns the noise fields and structure registry
   */
  @SuppressFBWarnings(
      value = "EI_EXPOSE_REP2",
      justification = "The plugin instance is the server's own singleton, shared by every command "
          + "that needs a scheduler or a data folder; copying it is not possible."
  )
  public Export(PluginConfig config, Plugin plugin, WorldEngine engine) {
    this.config = config;
    this.plugin = plugin;
    this.engine = engine;
  }

  @Override
  public void run(Player player, CommandArguments args) {
    if (config.getWorldEngine().isEnabled()) {
      reply(player, "<red>Refusing to export while the world engine is enabled: the chunks this "
          + "scan generates are only new once, and whatever happens to them now is permanent. "
          + "Export from a scratch world with <white>world-engine.enabled: false</white>.");
      return;
    }

    int size = intArg(args, SIZE, DEFAULT_SIZE);
    int resolution = intArg(args, RESOLUTION, DEFAULT_RESOLUTION);
    World world = player.getWorld();

    reply(player, "<gray>Sampling <white>" + size + "×" + size + "</white> of <white>"
        + world.getName() + "</white> at <white>" + resolution
        + "</white> blocks per sample. This generates terrain and will take a while.");

    new Scan(player, world, size, resolution).runTaskTimer(plugin, 1L, 1L);
  }

  private static int intArg(CommandArguments args, String name, int fallback) {
    Object value = args.get(name);
    return value instanceof Integer given ? given : fallback;
  }

  private void reply(Player player, String message) {
    player.sendRichMessage(config.getMessagePrefix() + message);
  }

  /**
   * The scan itself: a few chunks a tick until the area is covered, then one file.
   *
   * <p>Paced rather than looped because a three-kilometre square is thirty-five thousand chunks of
   * terrain generation. Doing that in one tick is a watchdog crash; doing it a handful of chunks at
   * a time is a server that stays playable while it works.
   */
  private final class Scan extends BukkitRunnable {

    private final Player player;
    private final World world;
    private final WorldSnapshot.Builder builder;
    private final WorldQuery query;
    private final Deque<long[]> pending = new ArrayDeque<>();
    private final List<CompletableFuture<Chunk>> inFlight = new ArrayList<>();
    private final int total;
    private final int originX;
    private final int originZ;
    private final int size;

    private int done;
    private int reportedTenths;

    private Scan(Player player, World world, int size, int resolution) {
      this.player = player;
      this.world = world;
      this.size = size;
      this.originX = -size / 2;
      this.originZ = -size / 2;
      this.builder = new WorldSnapshot.Builder(
          world.getName(), world.getSeed(), originX, originZ, size, resolution);
      this.query = new WorldQuery(
          config.getWorldEngine(),
          engine.fields(world),
          engine.structures(),
          engine.land(world),
          world.getSeed()
      );

      int fromChunkX = Math.floorDiv(originX, 16);
      int fromChunkZ = Math.floorDiv(originZ, 16);
      int toChunkX = Math.floorDiv(originX + builder.samplesPerSide() * resolution - 1, 16);
      int toChunkZ = Math.floorDiv(originZ + builder.samplesPerSide() * resolution - 1, 16);

      for (int chunkX = fromChunkX; chunkX <= toChunkX; chunkX++) {
        for (int chunkZ = fromChunkZ; chunkZ <= toChunkZ; chunkZ++) {
          pending.add(new long[] {chunkX, chunkZ});
        }
      }

      this.total = pending.size();
    }

    @Override
    public void run() {
      harvest();
      request();

      if (pending.isEmpty() && inFlight.isEmpty()) {
        cancel();
        finish();
      }
    }

    /** Reads every chunk load that has completed since the last tick. */
    private void harvest() {
      inFlight.removeIf(future -> {
        if (!future.isDone()) {
          return false;
        }

        try {
          sample(future.get().getChunkSnapshot(true, true, false));
        } catch (InterruptedException e) {
          Thread.currentThread().interrupt();
        } catch (Exception e) {
          // One unreadable chunk is a hole in the map, not a reason to lose the whole scan
          plugin.getLogger().log(Level.WARNING, "Export could not sample a chunk", e);
        }

        done++;
        report();
        return true;
      });
    }

    /** Tops the outstanding loads back up, a few chunks a tick. */
    private void request() {
      int started = 0;

      while (!pending.isEmpty() && inFlight.size() < IN_FLIGHT && started < CHUNKS_PER_TICK) {
        long[] chunk = pending.poll();
        inFlight.add(world.getChunkAtAsync((int) chunk[0], (int) chunk[1], true));
        started++;
      }
    }

    /** Records every sample whose block position falls inside one chunk. */
    private void sample(ChunkSnapshot chunk) {
      int resolution = builder.resolution();
      int baseX = chunk.getX() * 16;
      int baseZ = chunk.getZ() * 16;

      int fromSampleX = ceilDiv(baseX - originX, resolution);
      int fromSampleZ = ceilDiv(baseZ - originZ, resolution);

      for (int sampleX = fromSampleX; ; sampleX++) {
        int blockX = builder.blockXofSample(sampleX);
        if (blockX >= baseX + 16) {
          break;
        }
        if (blockX < baseX) {
          continue;
        }

        for (int sampleZ = fromSampleZ; ; sampleZ++) {
          int blockZ = builder.blockZofSample(sampleZ);
          if (blockZ >= baseZ + 16) {
            break;
          }
          if (blockZ < baseZ) {
            continue;
          }

          record(chunk, builder, sampleX, sampleZ, blockX - baseX, blockZ - baseZ, blockX, blockZ);
        }
      }

      // A request, not an order: the server drops the chunk when it is ready to, which keeps a
      // three-kilometre scan from holding the whole map in memory at once.
      world.unloadChunkRequest(chunk.getX(), chunk.getZ());
    }

    private void record(
        ChunkSnapshot chunk,
        WorldSnapshot.Builder into,
        int sampleX,
        int sampleZ,
        int localX,
        int localZ,
        int blockX,
        int blockZ
    ) {
      int surfaceY = chunk.getHighestBlockYAt(localX, localZ);
      int water = 0;

      // Walk down through the water rather than trusting sea level: a river cut into high ground
      // sits nowhere near it, and depth is what tells a ford from a lake.
      for (int y = surfaceY; y > world.getMinHeight(); y--) {
        if (chunk.getBlockType(localX, y, localZ) != Material.WATER) {
          break;
        }
        water++;
      }

      // The surface biome, which is what a designer sees; the land and rugged flags below come
      // from the engine's own lookup at sea level, which is what siting actually tests.
      String biomeKey = chunk.getBiome(localX, surfaceY, localZ).getKey().value();

      into.set(
          sampleX,
          sampleZ,
          surfaceY,
          water,
          TerrainClass.fromBiomeKey(biomeKey),
          query.isLand(blockX, blockZ),
          query.isRugged(blockX, blockZ),
          query.corruptionAt(blockX, blockZ),
          query.impactAt(blockX, blockZ)
      );
    }

    private void report() {
      int tenths = done * 10 / Math.max(1, total);
      if (tenths > reportedTenths) {
        reportedTenths = tenths;
        reply(player, "<gray>Sampled <white>" + tenths * 10 + "%</white> ("
            + done + " of " + total + " chunks)");
      }
    }

    /** Collects the sites, then writes the file off the main thread. */
    private void finish() {
      // Asked once for the whole area rather than per chunk: siting is pure arithmetic over the
      // seed, so a single radius covering the square is both cheaper and impossible to get
      // inconsistent between two chunks.
      int radius = (int) Math.ceil(size * Math.sqrt(2.0) / 2.0);
      List<PlannedSite> sites = query.sitesWithin(0, 0, radius);
      for (PlannedSite site : sites) {
        builder.add(site);
      }

      WorldSnapshot snapshot = builder.build();
      Path file = plugin.getDataFolder().toPath()
          .resolve(FOLDER)
          .resolve(String.format(Locale.ROOT, "%s-%d.nep", world.getName(), world.getSeed()));

      plugin.getServer().getScheduler().runTaskAsynchronously(plugin, () -> {
        try {
          snapshot.write(file);
          reply(player, "<green>Wrote <white>" + file.getFileName() + "</white> with "
              + sites.size() + " sites. Open it in the world planner.");
        } catch (IOException e) {
          plugin.getLogger().log(Level.SEVERE, "Could not write world snapshot " + file, e);
          reply(player, "<red>Sampling finished but the file could not be written; see the "
              + "server log.");
        }
      });
    }

    private static int ceilDiv(int value, int divisor) {
      return -Math.floorDiv(-value, divisor);
    }
  }
}
